language: ruby
rvm:
  - 1.9.3
script: "bundle exec rake db:drop db:create db:migrate spec"
bundler_args: --without development --path vendor/bundle
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  - DB=mysql
